### ISSUE TITLE
Declarations / Initial Values lost when compiling?

### ISSUE THREAD

**Issue by josefalanga** [YarnSpinnerTool/YarnSpinner-Console#25] opened 2023-06-20 19:48 UTC
Hello there. I'm collaborating with [YarnRunner-Python](https://github.com/relaypro-open/YarnRunner-Python) and I was wondering how would be the best approach to support initializing/declaring variables as the language server suggests. 

I see at the moment of compiling, `CompilationResult ` has a `Declarations` enumerable that doesn't get serialized, and  the class `Program` has a `InitialValues` property. AFAIK the `Program` class gets serialized with Google's Protobuf, but I don't understand/know how to retrieve those values. It's possible from a compiled `.yarnc` file get those back?

**Comment by McJones** [comment] 2023-06-29 02:50
Not sure I am understanding what the issue is sorry as the default declaration values are definitely being serialised.
To test this I made the following yarn file:

```
title: testvars
---
<<declare $testString = "default">>
<<declare $testNum = 1>>
<<declare $testBool = true>>
===
```

Compiled it via `ysc compile test.yarn` and then wrote the following to quickly test it:

```
public static void BrowseDecs(FileInfo compiledInput)
{
    var data = File.ReadAllBytes(compiledInput.FullName);
    var program = Yarn.Program.Parser.ParseFrom(data);

    if (program == null)
    {
        System.Console.WriteLine($"Unable to read {compiledInput.Name} as a yarn program");
        return;
    }

    System.Console.WriteLine($"{compiledInput.Name} contains {program.InitialValues.Count} declarations");
    foreach (var declaration in program.InitialValues)
    {
        System.Console.WriteLine(declaration.Key);
        var value = declaration.Value;

        switch (value.ValueCase)
        {
            case Yarn.Operand.ValueOneofCase.StringValue:
                System.Console.WriteLine("\ttype: String");
                System.Console.WriteLine($"\tinitial value: {value.StringValue}");
                break;
            case Yarn.Operand.ValueOneofCase.BoolValue:
                System.Console.WriteLine("\ttype: Boolean");
                System.Console.WriteLine($"\tinitial value: {value.BoolValue}");
                break;
            case Yarn.Operand.ValueOneofCase.FloatValue:
                System.Console.WriteLine("\ttype: Number");
                System.Console.WriteLine($"\tinitial value: {value.FloatValue}");
                break;
            default:
                System.Console.WriteLine($"unknown variable {value.ToString()}");
                break;
        }
    }
}
```

and when I run that I get the following:

```
test.yarnc contains 3 declarations
$testString
	type: String
	initial value: default
$testNum
	type: Number
	initial value: 1
$testBool
	type: Boolean
	initial value: True
```

I'm not sure how to read the program in Python but the `InitialValues` field in the protobuf is the entry point.

**Comment by McJones** [comment] 2023-06-29 04:42
Ok so I was curious, so first I added a binary browser command into ysc (`ysc browse-binary file.yarnc`) so you can more easily see what's inside the compiled output without having to open it up yourself.

I then quickly downloaded [YarnRunner-Python](https://github.com/relaypro-open/YarnRunner-Python) and added the following code to the runner to grab out the initial values

```python
def load_initial_vars(self):
        for key in self._compiled_yarn.initial_values:
            self.variables[key] = self._compiled_yarn.initial_values[key]
```

This didn't work because the version of the generated protobuf was out of date so I also updated that locally.
Then this worked and I verified it via compiling the following:

```
title: Start
---
<<declare $testString = "default">>
<<declare $testNum = 1>>
<<declare $testBool = true>>

The value of test bool {$testBool}
The value of test number {$testNum}
The value of test testString {$testString}
===
```

resulting in the following after running it through the python library:

```
The value of test bool bool_value: true

The value of test number float_value: 1.0

The value of test testString string_value: "default"

Woohoo! Our story is over!
```

So sorry to push this back onto you but it looks like this is on the YarnRunner-Python end not ysc.
I am going to close this issue now as I think this isn't our issue.
Feel free to open a new issue if I have totally misunderstood.

**Closed by McJones** 2023-06-29 04:42 UTC

**Comment by josefalanga** [comment] 2023-06-30 12:32
Thank you very much! This is enlightening and exactly what I needed.

I you don't mind I'd like to know exactly how you updated the generated protobuf? Last time I compared the [proto file](https://github.com/relaypro-open/YarnRunner-Python/blob/main/yarn_spinner.proto) with [yours](https://github.com/YarnSpinnerTool/YarnSpinner/blob/main/YarnSpinner/yarn_spinner.proto), were identical. Am I missing something?

**Comment by McJones** [comment] 2023-07-04 04:57
So I ran the standard `protoc --python_out=path --proto_path=path yarn_spinner.proto` command.
The proto files are indeed the same, but the generated python are not, the one I got from following the install instructions was missing the fields for the declarations so I assume it hadn't been regenerated in a while.
So after generating a new one then I could access the fields.
